version: '3.8'

services:
  yetAnotherDiskOpenAPI:
#    build: .
    container_name: yetAnotherDiskOpenAPI
    ports:
      - 80:80
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    depends_on:
      - postgres_db
    restart: always
    image: shbr_enrollment_yetanotherdiskopenapi:latest

  postgres_db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - /Users/khgamri/Documents/postgres_datapart:/var/lib/postgresql/data
    restart: always
